// Code generated by ent, DO NOT EDIT.

package accountplan

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldDescription, v))
}

// Price applies equality check predicate on the "price" field. It's identical to PriceEQ.
func Price(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldPrice, v))
}

// MaxCustomers applies equality check predicate on the "max_customers" field. It's identical to MaxCustomersEQ.
func MaxCustomers(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldMaxCustomers, v))
}

// MaxPlans applies equality check predicate on the "max_plans" field. It's identical to MaxPlansEQ.
func MaxPlans(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldMaxPlans, v))
}

// MaxProducts applies equality check predicate on the "max_products" field. It's identical to MaxProductsEQ.
func MaxProducts(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldMaxProducts, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionIsNil applies the IsNil predicate on the "description" field.
func DescriptionIsNil() predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIsNull(FieldDescription))
}

// DescriptionNotNil applies the NotNil predicate on the "description" field.
func DescriptionNotNil() predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotNull(FieldDescription))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldContainsFold(FieldDescription, v))
}

// PriceEQ applies the EQ predicate on the "price" field.
func PriceEQ(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldPrice, v))
}

// PriceNEQ applies the NEQ predicate on the "price" field.
func PriceNEQ(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldPrice, v))
}

// PriceIn applies the In predicate on the "price" field.
func PriceIn(vs ...float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldPrice, vs...))
}

// PriceNotIn applies the NotIn predicate on the "price" field.
func PriceNotIn(vs ...float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldPrice, vs...))
}

// PriceGT applies the GT predicate on the "price" field.
func PriceGT(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldPrice, v))
}

// PriceGTE applies the GTE predicate on the "price" field.
func PriceGTE(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldPrice, v))
}

// PriceLT applies the LT predicate on the "price" field.
func PriceLT(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldPrice, v))
}

// PriceLTE applies the LTE predicate on the "price" field.
func PriceLTE(v float64) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldPrice, v))
}

// MaxCustomersEQ applies the EQ predicate on the "max_customers" field.
func MaxCustomersEQ(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldMaxCustomers, v))
}

// MaxCustomersNEQ applies the NEQ predicate on the "max_customers" field.
func MaxCustomersNEQ(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldMaxCustomers, v))
}

// MaxCustomersIn applies the In predicate on the "max_customers" field.
func MaxCustomersIn(vs ...int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldMaxCustomers, vs...))
}

// MaxCustomersNotIn applies the NotIn predicate on the "max_customers" field.
func MaxCustomersNotIn(vs ...int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldMaxCustomers, vs...))
}

// MaxCustomersGT applies the GT predicate on the "max_customers" field.
func MaxCustomersGT(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldMaxCustomers, v))
}

// MaxCustomersGTE applies the GTE predicate on the "max_customers" field.
func MaxCustomersGTE(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldMaxCustomers, v))
}

// MaxCustomersLT applies the LT predicate on the "max_customers" field.
func MaxCustomersLT(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldMaxCustomers, v))
}

// MaxCustomersLTE applies the LTE predicate on the "max_customers" field.
func MaxCustomersLTE(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldMaxCustomers, v))
}

// MaxPlansEQ applies the EQ predicate on the "max_plans" field.
func MaxPlansEQ(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldMaxPlans, v))
}

// MaxPlansNEQ applies the NEQ predicate on the "max_plans" field.
func MaxPlansNEQ(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldMaxPlans, v))
}

// MaxPlansIn applies the In predicate on the "max_plans" field.
func MaxPlansIn(vs ...int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldMaxPlans, vs...))
}

// MaxPlansNotIn applies the NotIn predicate on the "max_plans" field.
func MaxPlansNotIn(vs ...int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldMaxPlans, vs...))
}

// MaxPlansGT applies the GT predicate on the "max_plans" field.
func MaxPlansGT(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldMaxPlans, v))
}

// MaxPlansGTE applies the GTE predicate on the "max_plans" field.
func MaxPlansGTE(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldMaxPlans, v))
}

// MaxPlansLT applies the LT predicate on the "max_plans" field.
func MaxPlansLT(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldMaxPlans, v))
}

// MaxPlansLTE applies the LTE predicate on the "max_plans" field.
func MaxPlansLTE(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldMaxPlans, v))
}

// MaxProductsEQ applies the EQ predicate on the "max_products" field.
func MaxProductsEQ(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldMaxProducts, v))
}

// MaxProductsNEQ applies the NEQ predicate on the "max_products" field.
func MaxProductsNEQ(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldMaxProducts, v))
}

// MaxProductsIn applies the In predicate on the "max_products" field.
func MaxProductsIn(vs ...int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldMaxProducts, vs...))
}

// MaxProductsNotIn applies the NotIn predicate on the "max_products" field.
func MaxProductsNotIn(vs ...int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldMaxProducts, vs...))
}

// MaxProductsGT applies the GT predicate on the "max_products" field.
func MaxProductsGT(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldMaxProducts, v))
}

// MaxProductsGTE applies the GTE predicate on the "max_products" field.
func MaxProductsGTE(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldMaxProducts, v))
}

// MaxProductsLT applies the LT predicate on the "max_products" field.
func MaxProductsLT(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldMaxProducts, v))
}

// MaxProductsLTE applies the LTE predicate on the "max_products" field.
func MaxProductsLTE(v int) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldMaxProducts, v))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountPlan {
	return predicate.AccountPlan(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.AccountPlan {
	return predicate.AccountPlan(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.AccountPlan {
	return predicate.AccountPlan(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountPlan) predicate.AccountPlan {
	return predicate.AccountPlan(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountPlan) predicate.AccountPlan {
	return predicate.AccountPlan(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountPlan) predicate.AccountPlan {
	return predicate.AccountPlan(sql.NotPredicates(p))
}
