// Code generated by ent, DO NOT EDIT.

package module

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the module type in the database.
	Label = "module"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccountPlans holds the string denoting the account_plans edge name in mutations.
	EdgeAccountPlans = "account_plans"
	// Table holds the table name of the module in the database.
	Table = "modules"
	// AccountPlansTable is the table that holds the account_plans relation/edge. The primary key declared below.
	AccountPlansTable = "account_plan_modules"
	// AccountPlansInverseTable is the table name for the AccountPlan entity.
	// It exists in this package in order to avoid circular dependency with the "accountplan" package.
	AccountPlansInverseTable = "account_plans"
)

// Columns holds all SQL columns for module fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldActive,
	FieldCreatedAt,
}

var (
	// AccountPlansPrimaryKey and AccountPlansColumn2 are the table columns denoting the
	// primary key for the account_plans relation (M2M).
	AccountPlansPrimaryKey = []string{"account_plan_id", "module_id"}
)

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Module queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccountPlansCount orders the results by account_plans count.
func ByAccountPlansCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountPlansStep(), opts...)
	}
}

// ByAccountPlans orders the results by account_plans terms.
func ByAccountPlans(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountPlansStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountPlansStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountPlansInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2M, true, AccountPlansTable, AccountPlansPrimaryKey...),
	)
}
