// Code generated by ent, DO NOT EDIT.

package subscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldID, id))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldClientID, v))
}

// PlanID applies equality check predicate on the "plan_id" field. It's identical to PlanIDEQ.
func PlanID(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPlanID, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStatus, v))
}

// ShipmentStatus applies equality check predicate on the "shipment_status" field. It's identical to ShipmentStatusEQ.
func ShipmentStatus(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldShipmentStatus, v))
}

// StartDate applies equality check predicate on the "start_date" field. It's identical to StartDateEQ.
func StartDate(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStartDate, v))
}

// NextBillingDate applies equality check predicate on the "next_billing_date" field. It's identical to NextBillingDateEQ.
func NextBillingDate(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldNextBillingDate, v))
}

// NextShipmentDate applies equality check predicate on the "next_shipment_date" field. It's identical to NextShipmentDateEQ.
func NextShipmentDate(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldNextShipmentDate, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDIsNil applies the IsNil predicate on the "client_id" field.
func ClientIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldClientID))
}

// ClientIDNotNil applies the NotNil predicate on the "client_id" field.
func ClientIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldClientID))
}

// PlanIDEQ applies the EQ predicate on the "plan_id" field.
func PlanIDEQ(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldPlanID, v))
}

// PlanIDNEQ applies the NEQ predicate on the "plan_id" field.
func PlanIDNEQ(v uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldPlanID, v))
}

// PlanIDIn applies the In predicate on the "plan_id" field.
func PlanIDIn(vs ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldPlanID, vs...))
}

// PlanIDNotIn applies the NotIn predicate on the "plan_id" field.
func PlanIDNotIn(vs ...uuid.UUID) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldPlanID, vs...))
}

// PlanIDIsNil applies the IsNil predicate on the "plan_id" field.
func PlanIDIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldPlanID))
}

// PlanIDNotNil applies the NotNil predicate on the "plan_id" field.
func PlanIDNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldPlanID))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldStatus, v))
}

// ShipmentStatusEQ applies the EQ predicate on the "shipment_status" field.
func ShipmentStatusEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldShipmentStatus, v))
}

// ShipmentStatusNEQ applies the NEQ predicate on the "shipment_status" field.
func ShipmentStatusNEQ(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldShipmentStatus, v))
}

// ShipmentStatusIn applies the In predicate on the "shipment_status" field.
func ShipmentStatusIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldShipmentStatus, vs...))
}

// ShipmentStatusNotIn applies the NotIn predicate on the "shipment_status" field.
func ShipmentStatusNotIn(vs ...string) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldShipmentStatus, vs...))
}

// ShipmentStatusGT applies the GT predicate on the "shipment_status" field.
func ShipmentStatusGT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldShipmentStatus, v))
}

// ShipmentStatusGTE applies the GTE predicate on the "shipment_status" field.
func ShipmentStatusGTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldShipmentStatus, v))
}

// ShipmentStatusLT applies the LT predicate on the "shipment_status" field.
func ShipmentStatusLT(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldShipmentStatus, v))
}

// ShipmentStatusLTE applies the LTE predicate on the "shipment_status" field.
func ShipmentStatusLTE(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldShipmentStatus, v))
}

// ShipmentStatusContains applies the Contains predicate on the "shipment_status" field.
func ShipmentStatusContains(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContains(FieldShipmentStatus, v))
}

// ShipmentStatusHasPrefix applies the HasPrefix predicate on the "shipment_status" field.
func ShipmentStatusHasPrefix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasPrefix(FieldShipmentStatus, v))
}

// ShipmentStatusHasSuffix applies the HasSuffix predicate on the "shipment_status" field.
func ShipmentStatusHasSuffix(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldHasSuffix(FieldShipmentStatus, v))
}

// ShipmentStatusEqualFold applies the EqualFold predicate on the "shipment_status" field.
func ShipmentStatusEqualFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldEqualFold(FieldShipmentStatus, v))
}

// ShipmentStatusContainsFold applies the ContainsFold predicate on the "shipment_status" field.
func ShipmentStatusContainsFold(v string) predicate.Subscription {
	return predicate.Subscription(sql.FieldContainsFold(FieldShipmentStatus, v))
}

// StartDateEQ applies the EQ predicate on the "start_date" field.
func StartDateEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldStartDate, v))
}

// StartDateNEQ applies the NEQ predicate on the "start_date" field.
func StartDateNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldStartDate, v))
}

// StartDateIn applies the In predicate on the "start_date" field.
func StartDateIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldStartDate, vs...))
}

// StartDateNotIn applies the NotIn predicate on the "start_date" field.
func StartDateNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldStartDate, vs...))
}

// StartDateGT applies the GT predicate on the "start_date" field.
func StartDateGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldStartDate, v))
}

// StartDateGTE applies the GTE predicate on the "start_date" field.
func StartDateGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldStartDate, v))
}

// StartDateLT applies the LT predicate on the "start_date" field.
func StartDateLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldStartDate, v))
}

// StartDateLTE applies the LTE predicate on the "start_date" field.
func StartDateLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldStartDate, v))
}

// NextBillingDateEQ applies the EQ predicate on the "next_billing_date" field.
func NextBillingDateEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldNextBillingDate, v))
}

// NextBillingDateNEQ applies the NEQ predicate on the "next_billing_date" field.
func NextBillingDateNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldNextBillingDate, v))
}

// NextBillingDateIn applies the In predicate on the "next_billing_date" field.
func NextBillingDateIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldNextBillingDate, vs...))
}

// NextBillingDateNotIn applies the NotIn predicate on the "next_billing_date" field.
func NextBillingDateNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldNextBillingDate, vs...))
}

// NextBillingDateGT applies the GT predicate on the "next_billing_date" field.
func NextBillingDateGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldNextBillingDate, v))
}

// NextBillingDateGTE applies the GTE predicate on the "next_billing_date" field.
func NextBillingDateGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldNextBillingDate, v))
}

// NextBillingDateLT applies the LT predicate on the "next_billing_date" field.
func NextBillingDateLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldNextBillingDate, v))
}

// NextBillingDateLTE applies the LTE predicate on the "next_billing_date" field.
func NextBillingDateLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldNextBillingDate, v))
}

// NextBillingDateIsNil applies the IsNil predicate on the "next_billing_date" field.
func NextBillingDateIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldNextBillingDate))
}

// NextBillingDateNotNil applies the NotNil predicate on the "next_billing_date" field.
func NextBillingDateNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldNextBillingDate))
}

// NextShipmentDateEQ applies the EQ predicate on the "next_shipment_date" field.
func NextShipmentDateEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldNextShipmentDate, v))
}

// NextShipmentDateNEQ applies the NEQ predicate on the "next_shipment_date" field.
func NextShipmentDateNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldNextShipmentDate, v))
}

// NextShipmentDateIn applies the In predicate on the "next_shipment_date" field.
func NextShipmentDateIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldNextShipmentDate, vs...))
}

// NextShipmentDateNotIn applies the NotIn predicate on the "next_shipment_date" field.
func NextShipmentDateNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldNextShipmentDate, vs...))
}

// NextShipmentDateGT applies the GT predicate on the "next_shipment_date" field.
func NextShipmentDateGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldNextShipmentDate, v))
}

// NextShipmentDateGTE applies the GTE predicate on the "next_shipment_date" field.
func NextShipmentDateGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldNextShipmentDate, v))
}

// NextShipmentDateLT applies the LT predicate on the "next_shipment_date" field.
func NextShipmentDateLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldNextShipmentDate, v))
}

// NextShipmentDateLTE applies the LTE predicate on the "next_shipment_date" field.
func NextShipmentDateLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldNextShipmentDate, v))
}

// NextShipmentDateIsNil applies the IsNil predicate on the "next_shipment_date" field.
func NextShipmentDateIsNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldIsNull(FieldNextShipmentDate))
}

// NextShipmentDateNotNil applies the NotNil predicate on the "next_shipment_date" field.
func NextShipmentDateNotNil() predicate.Subscription {
	return predicate.Subscription(sql.FieldNotNull(FieldNextShipmentDate))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Subscription {
	return predicate.Subscription(sql.FieldLTE(FieldCreatedAt, v))
}

// HasCustomer applies the HasEdge predicate on the "customer" edge.
func HasCustomer() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, CustomerTable, CustomerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCustomerWith applies the HasEdge predicate on the "customer" edge with a given conditions (other predicates).
func HasCustomerWith(preds ...predicate.Customer) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newCustomerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasPlan applies the HasEdge predicate on the "plan" edge.
func HasPlan() predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PlanTable, PlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPlanWith applies the HasEdge predicate on the "plan" edge with a given conditions (other predicates).
func HasPlanWith(preds ...predicate.Plan) predicate.Subscription {
	return predicate.Subscription(func(s *sql.Selector) {
		step := newPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Subscription) predicate.Subscription {
	return predicate.Subscription(sql.NotPredicates(p))
}
