// Code generated by ent, DO NOT EDIT.

package account

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the account type in the database.
	Label = "account"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldDocument holds the string denoting the document field in the database.
	FieldDocument = "document"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldAccountPlanID holds the string denoting the account_plan_id field in the database.
	FieldAccountPlanID = "account_plan_id"
	// FieldSubscriptionStatus holds the string denoting the subscription_status field in the database.
	FieldSubscriptionStatus = "subscription_status"
	// FieldSubscriptionExpiresAt holds the string denoting the subscription_expires_at field in the database.
	FieldSubscriptionExpiresAt = "subscription_expires_at"
	// FieldActive holds the string denoting the active field in the database.
	FieldActive = "active"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeAccountPlan holds the string denoting the account_plan edge name in mutations.
	EdgeAccountPlan = "account_plan"
	// Table holds the table name of the account in the database.
	Table = "accounts"
	// AccountPlanTable is the table that holds the account_plan relation/edge.
	AccountPlanTable = "accounts"
	// AccountPlanInverseTable is the table name for the AccountPlan entity.
	// It exists in this package in order to avoid circular dependency with the "accountplan" package.
	AccountPlanInverseTable = "account_plans"
	// AccountPlanColumn is the table column denoting the account_plan relation/edge.
	AccountPlanColumn = "account_plan_id"
)

// Columns holds all SQL columns for account fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldEmail,
	FieldDocument,
	FieldSlug,
	FieldAccountPlanID,
	FieldSubscriptionStatus,
	FieldSubscriptionExpiresAt,
	FieldActive,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// EmailValidator is a validator for the "email" field. It is called by the builders before save.
	EmailValidator func(string) error
	// SlugValidator is a validator for the "slug" field. It is called by the builders before save.
	SlugValidator func(string) error
	// DefaultActive holds the default value on creation for the "active" field.
	DefaultActive bool
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// SubscriptionStatus defines the type for the "subscription_status" enum field.
type SubscriptionStatus string

// SubscriptionStatusTrial is the default value of the SubscriptionStatus enum.
const DefaultSubscriptionStatus = SubscriptionStatusTrial

// SubscriptionStatus values.
const (
	SubscriptionStatusTrial     SubscriptionStatus = "trial"
	SubscriptionStatusActive    SubscriptionStatus = "active"
	SubscriptionStatusSuspended SubscriptionStatus = "suspended"
	SubscriptionStatusCancelled SubscriptionStatus = "cancelled"
)

func (ss SubscriptionStatus) String() string {
	return string(ss)
}

// SubscriptionStatusValidator is a validator for the "subscription_status" field enum values. It is called by the builders before save.
func SubscriptionStatusValidator(ss SubscriptionStatus) error {
	switch ss {
	case SubscriptionStatusTrial, SubscriptionStatusActive, SubscriptionStatusSuspended, SubscriptionStatusCancelled:
		return nil
	default:
		return fmt.Errorf("account: invalid enum value for subscription_status field: %q", ss)
	}
}

// OrderOption defines the ordering options for the Account queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByDocument orders the results by the document field.
func ByDocument(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDocument, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByAccountPlanID orders the results by the account_plan_id field.
func ByAccountPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountPlanID, opts...).ToFunc()
}

// BySubscriptionStatus orders the results by the subscription_status field.
func BySubscriptionStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionStatus, opts...).ToFunc()
}

// BySubscriptionExpiresAt orders the results by the subscription_expires_at field.
func BySubscriptionExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSubscriptionExpiresAt, opts...).ToFunc()
}

// ByActive orders the results by the active field.
func ByActive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldActive, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAccountPlanField orders the results by account_plan field.
func ByAccountPlanField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountPlanStep(), sql.OrderByField(field, opts...))
	}
}
func newAccountPlanStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountPlanInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, AccountPlanTable, AccountPlanColumn),
	)
}
