// Code generated by ent, DO NOT EDIT.

package account

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// Email applies equality check predicate on the "email" field. It's identical to EmailEQ.
func Email(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldEmail, v))
}

// Document applies equality check predicate on the "document" field. It's identical to DocumentEQ.
func Document(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDocument, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSlug, v))
}

// AccountPlanID applies equality check predicate on the "account_plan_id" field. It's identical to AccountPlanIDEQ.
func AccountPlanID(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccountPlanID, v))
}

// SubscriptionExpiresAt applies equality check predicate on the "subscription_expires_at" field. It's identical to SubscriptionExpiresAtEQ.
func SubscriptionExpiresAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSubscriptionExpiresAt, v))
}

// Active applies equality check predicate on the "active" field. It's identical to ActiveEQ.
func Active(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldActive, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldName, v))
}

// EmailEQ applies the EQ predicate on the "email" field.
func EmailEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldEmail, v))
}

// EmailNEQ applies the NEQ predicate on the "email" field.
func EmailNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldEmail, v))
}

// EmailIn applies the In predicate on the "email" field.
func EmailIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldEmail, vs...))
}

// EmailNotIn applies the NotIn predicate on the "email" field.
func EmailNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldEmail, vs...))
}

// EmailGT applies the GT predicate on the "email" field.
func EmailGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldEmail, v))
}

// EmailGTE applies the GTE predicate on the "email" field.
func EmailGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldEmail, v))
}

// EmailLT applies the LT predicate on the "email" field.
func EmailLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldEmail, v))
}

// EmailLTE applies the LTE predicate on the "email" field.
func EmailLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldEmail, v))
}

// EmailContains applies the Contains predicate on the "email" field.
func EmailContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldEmail, v))
}

// EmailHasPrefix applies the HasPrefix predicate on the "email" field.
func EmailHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldEmail, v))
}

// EmailHasSuffix applies the HasSuffix predicate on the "email" field.
func EmailHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldEmail, v))
}

// EmailEqualFold applies the EqualFold predicate on the "email" field.
func EmailEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldEmail, v))
}

// EmailContainsFold applies the ContainsFold predicate on the "email" field.
func EmailContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldEmail, v))
}

// DocumentEQ applies the EQ predicate on the "document" field.
func DocumentEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDocument, v))
}

// DocumentNEQ applies the NEQ predicate on the "document" field.
func DocumentNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDocument, v))
}

// DocumentIn applies the In predicate on the "document" field.
func DocumentIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldDocument, vs...))
}

// DocumentNotIn applies the NotIn predicate on the "document" field.
func DocumentNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldDocument, vs...))
}

// DocumentGT applies the GT predicate on the "document" field.
func DocumentGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldDocument, v))
}

// DocumentGTE applies the GTE predicate on the "document" field.
func DocumentGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldDocument, v))
}

// DocumentLT applies the LT predicate on the "document" field.
func DocumentLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldDocument, v))
}

// DocumentLTE applies the LTE predicate on the "document" field.
func DocumentLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldDocument, v))
}

// DocumentContains applies the Contains predicate on the "document" field.
func DocumentContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldDocument, v))
}

// DocumentHasPrefix applies the HasPrefix predicate on the "document" field.
func DocumentHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldDocument, v))
}

// DocumentHasSuffix applies the HasSuffix predicate on the "document" field.
func DocumentHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldDocument, v))
}

// DocumentIsNil applies the IsNil predicate on the "document" field.
func DocumentIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldDocument))
}

// DocumentNotNil applies the NotNil predicate on the "document" field.
func DocumentNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldDocument))
}

// DocumentEqualFold applies the EqualFold predicate on the "document" field.
func DocumentEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldDocument, v))
}

// DocumentContainsFold applies the ContainsFold predicate on the "document" field.
func DocumentContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldDocument, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldSlug, v))
}

// AccountPlanIDEQ applies the EQ predicate on the "account_plan_id" field.
func AccountPlanIDEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldAccountPlanID, v))
}

// AccountPlanIDNEQ applies the NEQ predicate on the "account_plan_id" field.
func AccountPlanIDNEQ(v uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldAccountPlanID, v))
}

// AccountPlanIDIn applies the In predicate on the "account_plan_id" field.
func AccountPlanIDIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldAccountPlanID, vs...))
}

// AccountPlanIDNotIn applies the NotIn predicate on the "account_plan_id" field.
func AccountPlanIDNotIn(vs ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldAccountPlanID, vs...))
}

// AccountPlanIDIsNil applies the IsNil predicate on the "account_plan_id" field.
func AccountPlanIDIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldAccountPlanID))
}

// AccountPlanIDNotNil applies the NotNil predicate on the "account_plan_id" field.
func AccountPlanIDNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldAccountPlanID))
}

// SubscriptionStatusEQ applies the EQ predicate on the "subscription_status" field.
func SubscriptionStatusEQ(v SubscriptionStatus) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSubscriptionStatus, v))
}

// SubscriptionStatusNEQ applies the NEQ predicate on the "subscription_status" field.
func SubscriptionStatusNEQ(v SubscriptionStatus) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSubscriptionStatus, v))
}

// SubscriptionStatusIn applies the In predicate on the "subscription_status" field.
func SubscriptionStatusIn(vs ...SubscriptionStatus) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSubscriptionStatus, vs...))
}

// SubscriptionStatusNotIn applies the NotIn predicate on the "subscription_status" field.
func SubscriptionStatusNotIn(vs ...SubscriptionStatus) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSubscriptionStatus, vs...))
}

// SubscriptionExpiresAtEQ applies the EQ predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSubscriptionExpiresAt, v))
}

// SubscriptionExpiresAtNEQ applies the NEQ predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSubscriptionExpiresAt, v))
}

// SubscriptionExpiresAtIn applies the In predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSubscriptionExpiresAt, vs...))
}

// SubscriptionExpiresAtNotIn applies the NotIn predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSubscriptionExpiresAt, vs...))
}

// SubscriptionExpiresAtGT applies the GT predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSubscriptionExpiresAt, v))
}

// SubscriptionExpiresAtGTE applies the GTE predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSubscriptionExpiresAt, v))
}

// SubscriptionExpiresAtLT applies the LT predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSubscriptionExpiresAt, v))
}

// SubscriptionExpiresAtLTE applies the LTE predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSubscriptionExpiresAt, v))
}

// SubscriptionExpiresAtIsNil applies the IsNil predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldSubscriptionExpiresAt))
}

// SubscriptionExpiresAtNotNil applies the NotNil predicate on the "subscription_expires_at" field.
func SubscriptionExpiresAtNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldSubscriptionExpiresAt))
}

// ActiveEQ applies the EQ predicate on the "active" field.
func ActiveEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldActive, v))
}

// ActiveNEQ applies the NEQ predicate on the "active" field.
func ActiveNEQ(v bool) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldActive, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// HasAccountPlan applies the HasEdge predicate on the "account_plan" edge.
func HasAccountPlan() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AccountPlanTable, AccountPlanColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountPlanWith applies the HasEdge predicate on the "account_plan" edge with a given conditions (other predicates).
func HasAccountPlanWith(preds ...predicate.AccountPlan) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newAccountPlanStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
