// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "document", Type: field.TypeString, Nullable: true},
		{Name: "slug", Type: field.TypeString, Unique: true},
		{Name: "subscription_status", Type: field.TypeEnum, Enums: []string{"trial", "active", "suspended", "cancelled"}, Default: "trial"},
		{Name: "subscription_expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "account_plan_id", Type: field.TypeUUID, Nullable: true},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "accounts_account_plans_accounts",
				Columns:    []*schema.Column{AccountsColumns[9]},
				RefColumns: []*schema.Column{AccountPlansColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// AccountDomainsColumns holds the columns for the "account_domains" table.
	AccountDomainsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "domain", Type: field.TypeString, Unique: true},
		{Name: "account_id", Type: field.TypeUUID},
	}
	// AccountDomainsTable holds the schema information for the "account_domains" table.
	AccountDomainsTable = &schema.Table{
		Name:       "account_domains",
		Columns:    AccountDomainsColumns,
		PrimaryKey: []*schema.Column{AccountDomainsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_domains_accounts_domains",
				Columns:    []*schema.Column{AccountDomainsColumns[2]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// AccountPlansColumns holds the columns for the "account_plans" table.
	AccountPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "price", Type: field.TypeFloat64},
		{Name: "max_customers", Type: field.TypeInt, Default: 0},
		{Name: "max_plans", Type: field.TypeInt, Default: 0},
		{Name: "max_products", Type: field.TypeInt, Default: 0},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// AccountPlansTable holds the schema information for the "account_plans" table.
	AccountPlansTable = &schema.Table{
		Name:       "account_plans",
		Columns:    AccountPlansColumns,
		PrimaryKey: []*schema.Column{AccountPlansColumns[0]},
	}
	// CustomersColumns holds the columns for the "customers" table.
	CustomersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "phone", Type: field.TypeString, Nullable: true},
		{Name: "document", Type: field.TypeString, Unique: true, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "address", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// CustomersTable holds the schema information for the "customers" table.
	CustomersTable = &schema.Table{
		Name:       "customers",
		Columns:    CustomersColumns,
		PrimaryKey: []*schema.Column{CustomersColumns[0]},
	}
	// ModulesColumns holds the columns for the "modules" table.
	ModulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ModulesTable holds the schema information for the "modules" table.
	ModulesTable = &schema.Table{
		Name:       "modules",
		Columns:    ModulesColumns,
		PrimaryKey: []*schema.Column{ModulesColumns[0]},
	}
	// PlansColumns holds the columns for the "plans" table.
	PlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "product_value", Type: field.TypeFloat64, Default: 0},
		{Name: "discount_value", Type: field.TypeFloat64, Default: 0},
		{Name: "price", Type: field.TypeFloat64, Default: 0},
		{Name: "interval_days", Type: field.TypeInt, Default: 30},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// PlansTable holds the schema information for the "plans" table.
	PlansTable = &schema.Table{
		Name:       "plans",
		Columns:    PlansColumns,
		PrimaryKey: []*schema.Column{PlansColumns[0]},
	}
	// ProductsColumns holds the columns for the "products" table.
	ProductsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "code", Type: field.TypeString, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Nullable: true},
		{Name: "cost_price", Type: field.TypeFloat64, Default: 0},
		{Name: "category", Type: field.TypeString, Nullable: true},
		{Name: "image_url", Type: field.TypeString, Nullable: true},
		{Name: "active", Type: field.TypeBool, Default: true},
		{Name: "created_at", Type: field.TypeTime},
	}
	// ProductsTable holds the schema information for the "products" table.
	ProductsTable = &schema.Table{
		Name:       "products",
		Columns:    ProductsColumns,
		PrimaryKey: []*schema.Column{ProductsColumns[0]},
	}
	// SubscriptionsColumns holds the columns for the "subscriptions" table.
	SubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "shipment_status", Type: field.TypeString, Default: "pending"},
		{Name: "start_date", Type: field.TypeTime},
		{Name: "next_billing_date", Type: field.TypeTime, Nullable: true},
		{Name: "next_shipment_date", Type: field.TypeTime, Nullable: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "customer_id", Type: field.TypeUUID, Nullable: true},
		{Name: "plan_id", Type: field.TypeUUID, Nullable: true},
	}
	// SubscriptionsTable holds the schema information for the "subscriptions" table.
	SubscriptionsTable = &schema.Table{
		Name:       "subscriptions",
		Columns:    SubscriptionsColumns,
		PrimaryKey: []*schema.Column{SubscriptionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "subscriptions_customers_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[7]},
				RefColumns: []*schema.Column{CustomersColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "subscriptions_plans_subscriptions",
				Columns:    []*schema.Column{SubscriptionsColumns[8]},
				RefColumns: []*schema.Column{PlansColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
	}
	// SystemUsersColumns holds the columns for the "system_users" table.
	SystemUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"individual", "corporate", "system"}, Default: "individual"},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "operations"}, Default: "admin"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// SystemUsersTable holds the schema information for the "system_users" table.
	SystemUsersTable = &schema.Table{
		Name:       "system_users",
		Columns:    SystemUsersColumns,
		PrimaryKey: []*schema.Column{SystemUsersColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "name", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
		{Name: "role", Type: field.TypeEnum, Enums: []string{"admin", "operations"}, Default: "admin"},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// AccountPlanModulesColumns holds the columns for the "account_plan_modules" table.
	AccountPlanModulesColumns = []*schema.Column{
		{Name: "account_plan_id", Type: field.TypeUUID},
		{Name: "module_id", Type: field.TypeUUID},
	}
	// AccountPlanModulesTable holds the schema information for the "account_plan_modules" table.
	AccountPlanModulesTable = &schema.Table{
		Name:       "account_plan_modules",
		Columns:    AccountPlanModulesColumns,
		PrimaryKey: []*schema.Column{AccountPlanModulesColumns[0], AccountPlanModulesColumns[1]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "account_plan_modules_account_plan_id",
				Columns:    []*schema.Column{AccountPlanModulesColumns[0]},
				RefColumns: []*schema.Column{AccountPlansColumns[0]},
				OnDelete:   schema.Cascade,
			},
			{
				Symbol:     "account_plan_modules_module_id",
				Columns:    []*schema.Column{AccountPlanModulesColumns[1]},
				RefColumns: []*schema.Column{ModulesColumns[0]},
				OnDelete:   schema.Cascade,
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		AccountDomainsTable,
		AccountPlansTable,
		CustomersTable,
		ModulesTable,
		PlansTable,
		ProductsTable,
		SubscriptionsTable,
		SystemUsersTable,
		UsersTable,
		AccountPlanModulesTable,
	}
)

func init() {
	AccountsTable.ForeignKeys[0].RefTable = AccountPlansTable
	AccountDomainsTable.ForeignKeys[0].RefTable = AccountsTable
	SubscriptionsTable.ForeignKeys[0].RefTable = CustomersTable
	SubscriptionsTable.ForeignKeys[1].RefTable = PlansTable
	AccountPlanModulesTable.ForeignKeys[0].RefTable = AccountPlansTable
	AccountPlanModulesTable.ForeignKeys[1].RefTable = ModulesTable
}
