// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/accountplan"
)

// AccountPlan is the model entity for the AccountPlan schema.
type AccountPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Price holds the value of the "price" field.
	Price float64 `json:"price,omitempty"`
	// MaxCustomers holds the value of the "max_customers" field.
	MaxCustomers int `json:"max_customers,omitempty"`
	// MaxPlans holds the value of the "max_plans" field.
	MaxPlans int `json:"max_plans,omitempty"`
	// MaxProducts holds the value of the "max_products" field.
	MaxProducts int `json:"max_products,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountPlanQuery when eager-loading is set.
	Edges        AccountPlanEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountPlanEdges holds the relations/edges for other nodes in the graph.
type AccountPlanEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e AccountPlanEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountplan.FieldActive:
			values[i] = new(sql.NullBool)
		case accountplan.FieldPrice:
			values[i] = new(sql.NullFloat64)
		case accountplan.FieldMaxCustomers, accountplan.FieldMaxPlans, accountplan.FieldMaxProducts:
			values[i] = new(sql.NullInt64)
		case accountplan.FieldName, accountplan.FieldDescription:
			values[i] = new(sql.NullString)
		case accountplan.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case accountplan.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountPlan fields.
func (_m *AccountPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountplan.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case accountplan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case accountplan.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case accountplan.FieldPrice:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field price", values[i])
			} else if value.Valid {
				_m.Price = value.Float64
			}
		case accountplan.FieldMaxCustomers:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_customers", values[i])
			} else if value.Valid {
				_m.MaxCustomers = int(value.Int64)
			}
		case accountplan.FieldMaxPlans:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_plans", values[i])
			} else if value.Valid {
				_m.MaxPlans = int(value.Int64)
			}
		case accountplan.FieldMaxProducts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_products", values[i])
			} else if value.Valid {
				_m.MaxProducts = int(value.Int64)
			}
		case accountplan.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case accountplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountPlan.
// This includes values selected through modifiers, order, etc.
func (_m *AccountPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the AccountPlan entity.
func (_m *AccountPlan) QueryAccounts() *AccountQuery {
	return NewAccountPlanClient(_m.config).QueryAccounts(_m)
}

// Update returns a builder for updating this AccountPlan.
// Note that you need to call AccountPlan.Unwrap() before calling this method if this AccountPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountPlan) Update() *AccountPlanUpdateOne {
	return NewAccountPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountPlan) Unwrap() *AccountPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountPlan) String() string {
	var builder strings.Builder
	builder.WriteString("AccountPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("price=")
	builder.WriteString(fmt.Sprintf("%v", _m.Price))
	builder.WriteString(", ")
	builder.WriteString("max_customers=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxCustomers))
	builder.WriteString(", ")
	builder.WriteString("max_plans=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxPlans))
	builder.WriteString(", ")
	builder.WriteString("max_products=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxProducts))
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountPlans is a parsable slice of AccountPlan.
type AccountPlans []*AccountPlan
