// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/account"
	"github.com/joaofilippe/subclub/ent/accountdomain"
	"github.com/joaofilippe/subclub/ent/accountplan"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (_c *AccountCreate) SetName(v string) *AccountCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *AccountCreate) SetEmail(v string) *AccountCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetDocument sets the "document" field.
func (_c *AccountCreate) SetDocument(v string) *AccountCreate {
	_c.mutation.SetDocument(v)
	return _c
}

// SetNillableDocument sets the "document" field if the given value is not nil.
func (_c *AccountCreate) SetNillableDocument(v *string) *AccountCreate {
	if v != nil {
		_c.SetDocument(*v)
	}
	return _c
}

// SetSlug sets the "slug" field.
func (_c *AccountCreate) SetSlug(v string) *AccountCreate {
	_c.mutation.SetSlug(v)
	return _c
}

// SetAccountPlanID sets the "account_plan_id" field.
func (_c *AccountCreate) SetAccountPlanID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetAccountPlanID(v)
	return _c
}

// SetNillableAccountPlanID sets the "account_plan_id" field if the given value is not nil.
func (_c *AccountCreate) SetNillableAccountPlanID(v *uuid.UUID) *AccountCreate {
	if v != nil {
		_c.SetAccountPlanID(*v)
	}
	return _c
}

// SetSubscriptionStatus sets the "subscription_status" field.
func (_c *AccountCreate) SetSubscriptionStatus(v account.SubscriptionStatus) *AccountCreate {
	_c.mutation.SetSubscriptionStatus(v)
	return _c
}

// SetNillableSubscriptionStatus sets the "subscription_status" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSubscriptionStatus(v *account.SubscriptionStatus) *AccountCreate {
	if v != nil {
		_c.SetSubscriptionStatus(*v)
	}
	return _c
}

// SetSubscriptionExpiresAt sets the "subscription_expires_at" field.
func (_c *AccountCreate) SetSubscriptionExpiresAt(v time.Time) *AccountCreate {
	_c.mutation.SetSubscriptionExpiresAt(v)
	return _c
}

// SetNillableSubscriptionExpiresAt sets the "subscription_expires_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableSubscriptionExpiresAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetSubscriptionExpiresAt(*v)
	}
	return _c
}

// SetActive sets the "active" field.
func (_c *AccountCreate) SetActive(v bool) *AccountCreate {
	_c.mutation.SetActive(v)
	return _c
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_c *AccountCreate) SetNillableActive(v *bool) *AccountCreate {
	if v != nil {
		_c.SetActive(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountCreate) SetCreatedAt(v time.Time) *AccountCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountCreate) SetNillableCreatedAt(v *time.Time) *AccountCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AccountCreate) SetID(v uuid.UUID) *AccountCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountCreate) SetNillableID(v *uuid.UUID) *AccountCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAccountPlan sets the "account_plan" edge to the AccountPlan entity.
func (_c *AccountCreate) SetAccountPlan(v *AccountPlan) *AccountCreate {
	return _c.SetAccountPlanID(v.ID)
}

// AddDomainIDs adds the "domains" edge to the AccountDomain entity by IDs.
func (_c *AccountCreate) AddDomainIDs(ids ...uuid.UUID) *AccountCreate {
	_c.mutation.AddDomainIDs(ids...)
	return _c
}

// AddDomains adds the "domains" edges to the AccountDomain entity.
func (_c *AccountCreate) AddDomains(v ...*AccountDomain) *AccountCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDomainIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (_c *AccountCreate) Mutation() *AccountMutation {
	return _c.mutation
}

// Save creates the Account in the database.
func (_c *AccountCreate) Save(ctx context.Context) (*Account, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountCreate) defaults() {
	if _, ok := _c.mutation.SubscriptionStatus(); !ok {
		v := account.DefaultSubscriptionStatus
		_c.mutation.SetSubscriptionStatus(v)
	}
	if _, ok := _c.mutation.Active(); !ok {
		v := account.DefaultActive
		_c.mutation.SetActive(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := account.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountCreate) check() error {
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "Account.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := account.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Account.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "Account.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := account.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "Account.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Slug(); !ok {
		return &ValidationError{Name: "slug", err: errors.New(`ent: missing required field "Account.slug"`)}
	}
	if v, ok := _c.mutation.Slug(); ok {
		if err := account.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Account.slug": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubscriptionStatus(); !ok {
		return &ValidationError{Name: "subscription_status", err: errors.New(`ent: missing required field "Account.subscription_status"`)}
	}
	if v, ok := _c.mutation.SubscriptionStatus(); ok {
		if err := account.SubscriptionStatusValidator(v); err != nil {
			return &ValidationError{Name: "subscription_status", err: fmt.Errorf(`ent: validator failed for field "Account.subscription_status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Active(); !ok {
		return &ValidationError{Name: "active", err: errors.New(`ent: missing required field "Account.active"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	return nil
}

func (_c *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(account.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(account.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Document(); ok {
		_spec.SetField(account.FieldDocument, field.TypeString, value)
		_node.Document = value
	}
	if value, ok := _c.mutation.Slug(); ok {
		_spec.SetField(account.FieldSlug, field.TypeString, value)
		_node.Slug = value
	}
	if value, ok := _c.mutation.SubscriptionStatus(); ok {
		_spec.SetField(account.FieldSubscriptionStatus, field.TypeEnum, value)
		_node.SubscriptionStatus = value
	}
	if value, ok := _c.mutation.SubscriptionExpiresAt(); ok {
		_spec.SetField(account.FieldSubscriptionExpiresAt, field.TypeTime, value)
		_node.SubscriptionExpiresAt = &value
	}
	if value, ok := _c.mutation.Active(); ok {
		_spec.SetField(account.FieldActive, field.TypeBool, value)
		_node.Active = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AccountPlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   account.AccountPlanTable,
			Columns: []string{account.AccountPlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountPlanID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DomainsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.DomainsTable,
			Columns: []string{account.DomainsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountdomain.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (_c *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Account, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
