// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/joaofilippe/subclub/ent/accountdomain"
	"github.com/joaofilippe/subclub/ent/predicate"
)

// AccountDomainDelete is the builder for deleting a AccountDomain entity.
type AccountDomainDelete struct {
	config
	hooks    []Hook
	mutation *AccountDomainMutation
}

// Where appends a list predicates to the AccountDomainDelete builder.
func (_d *AccountDomainDelete) Where(ps ...predicate.AccountDomain) *AccountDomainDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *AccountDomainDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountDomainDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *AccountDomainDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(accountdomain.Table, sqlgraph.NewFieldSpec(accountdomain.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// AccountDomainDeleteOne is the builder for deleting a single AccountDomain entity.
type AccountDomainDeleteOne struct {
	_d *AccountDomainDelete
}

// Where appends a list predicates to the AccountDomainDelete builder.
func (_d *AccountDomainDeleteOne) Where(ps ...predicate.AccountDomain) *AccountDomainDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *AccountDomainDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{accountdomain.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *AccountDomainDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
