// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/account"
	"github.com/joaofilippe/subclub/ent/accountdomain"
)

// AccountDomainCreate is the builder for creating a AccountDomain entity.
type AccountDomainCreate struct {
	config
	mutation *AccountDomainMutation
	hooks    []Hook
}

// SetDomain sets the "domain" field.
func (_c *AccountDomainCreate) SetDomain(v string) *AccountDomainCreate {
	_c.mutation.SetDomain(v)
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountDomainCreate) SetAccountID(v uuid.UUID) *AccountDomainCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetID sets the "id" field.
func (_c *AccountDomainCreate) SetID(v uuid.UUID) *AccountDomainCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AccountDomainCreate) SetNillableID(v *uuid.UUID) *AccountDomainCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAccount sets the "account" edge to the Account entity.
func (_c *AccountDomainCreate) SetAccount(v *Account) *AccountDomainCreate {
	return _c.SetAccountID(v.ID)
}

// Mutation returns the AccountDomainMutation object of the builder.
func (_c *AccountDomainCreate) Mutation() *AccountDomainMutation {
	return _c.mutation
}

// Save creates the AccountDomain in the database.
func (_c *AccountDomainCreate) Save(ctx context.Context) (*AccountDomain, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountDomainCreate) SaveX(ctx context.Context) *AccountDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountDomainCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountDomainCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountDomainCreate) defaults() {
	if _, ok := _c.mutation.ID(); !ok {
		v := accountdomain.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountDomainCreate) check() error {
	if _, ok := _c.mutation.Domain(); !ok {
		return &ValidationError{Name: "domain", err: errors.New(`ent: missing required field "AccountDomain.domain"`)}
	}
	if v, ok := _c.mutation.Domain(); ok {
		if err := accountdomain.DomainValidator(v); err != nil {
			return &ValidationError{Name: "domain", err: fmt.Errorf(`ent: validator failed for field "AccountDomain.domain": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountDomain.account_id"`)}
	}
	if len(_c.mutation.AccountIDs()) == 0 {
		return &ValidationError{Name: "account", err: errors.New(`ent: missing required edge "AccountDomain.account"`)}
	}
	return nil
}

func (_c *AccountDomainCreate) sqlSave(ctx context.Context) (*AccountDomain, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountDomainCreate) createSpec() (*AccountDomain, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountDomain{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountdomain.Table, sqlgraph.NewFieldSpec(accountdomain.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Domain(); ok {
		_spec.SetField(accountdomain.FieldDomain, field.TypeString, value)
		_node.Domain = value
	}
	if nodes := _c.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   accountdomain.AccountTable,
			Columns: []string{accountdomain.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountDomainCreateBulk is the builder for creating many AccountDomain entities in bulk.
type AccountDomainCreateBulk struct {
	config
	err      error
	builders []*AccountDomainCreate
}

// Save creates the AccountDomain entities in the database.
func (_c *AccountDomainCreateBulk) Save(ctx context.Context) ([]*AccountDomain, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountDomain, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountDomainMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountDomainCreateBulk) SaveX(ctx context.Context) []*AccountDomain {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountDomainCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountDomainCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
