// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/account"
	"github.com/joaofilippe/subclub/ent/accountplan"
)

// Account is the model entity for the Account schema.
type Account struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Document holds the value of the "document" field.
	Document string `json:"document,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// AccountPlanID holds the value of the "account_plan_id" field.
	AccountPlanID uuid.UUID `json:"account_plan_id,omitempty"`
	// SubscriptionStatus holds the value of the "subscription_status" field.
	SubscriptionStatus account.SubscriptionStatus `json:"subscription_status,omitempty"`
	// SubscriptionExpiresAt holds the value of the "subscription_expires_at" field.
	SubscriptionExpiresAt *time.Time `json:"subscription_expires_at,omitempty"`
	// Active holds the value of the "active" field.
	Active bool `json:"active,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AccountQuery when eager-loading is set.
	Edges        AccountEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AccountEdges holds the relations/edges for other nodes in the graph.
type AccountEdges struct {
	// AccountPlan holds the value of the account_plan edge.
	AccountPlan *AccountPlan `json:"account_plan,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountPlanOrErr returns the AccountPlan value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AccountEdges) AccountPlanOrErr() (*AccountPlan, error) {
	if e.AccountPlan != nil {
		return e.AccountPlan, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: accountplan.Label}
	}
	return nil, &NotLoadedError{edge: "account_plan"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Account) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case account.FieldActive:
			values[i] = new(sql.NullBool)
		case account.FieldName, account.FieldEmail, account.FieldDocument, account.FieldSlug, account.FieldSubscriptionStatus:
			values[i] = new(sql.NullString)
		case account.FieldSubscriptionExpiresAt, account.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case account.FieldID, account.FieldAccountPlanID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Account fields.
func (_m *Account) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case account.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case account.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case account.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = value.String
			}
		case account.FieldDocument:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field document", values[i])
			} else if value.Valid {
				_m.Document = value.String
			}
		case account.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case account.FieldAccountPlanID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field account_plan_id", values[i])
			} else if value != nil {
				_m.AccountPlanID = *value
			}
		case account.FieldSubscriptionStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_status", values[i])
			} else if value.Valid {
				_m.SubscriptionStatus = account.SubscriptionStatus(value.String)
			}
		case account.FieldSubscriptionExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field subscription_expires_at", values[i])
			} else if value.Valid {
				_m.SubscriptionExpiresAt = new(time.Time)
				*_m.SubscriptionExpiresAt = value.Time
			}
		case account.FieldActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field active", values[i])
			} else if value.Valid {
				_m.Active = value.Bool
			}
		case account.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Account.
// This includes values selected through modifiers, order, etc.
func (_m *Account) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccountPlan queries the "account_plan" edge of the Account entity.
func (_m *Account) QueryAccountPlan() *AccountPlanQuery {
	return NewAccountClient(_m.config).QueryAccountPlan(_m)
}

// Update returns a builder for updating this Account.
// Note that you need to call Account.Unwrap() before calling this method if this Account
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Account) Update() *AccountUpdateOne {
	return NewAccountClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Account entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Account) Unwrap() *Account {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Account is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Account) String() string {
	var builder strings.Builder
	builder.WriteString("Account(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(_m.Email)
	builder.WriteString(", ")
	builder.WriteString("document=")
	builder.WriteString(_m.Document)
	builder.WriteString(", ")
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("account_plan_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountPlanID))
	builder.WriteString(", ")
	builder.WriteString("subscription_status=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscriptionStatus))
	builder.WriteString(", ")
	if v := _m.SubscriptionExpiresAt; v != nil {
		builder.WriteString("subscription_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("active=")
	builder.WriteString(fmt.Sprintf("%v", _m.Active))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Accounts is a parsable slice of Account.
type Accounts []*Account
