// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/accountplan"
	"github.com/joaofilippe/subclub/ent/module"
	"github.com/joaofilippe/subclub/ent/predicate"
)

// ModuleUpdate is the builder for updating Module entities.
type ModuleUpdate struct {
	config
	hooks    []Hook
	mutation *ModuleMutation
}

// Where appends a list predicates to the ModuleUpdate builder.
func (_u *ModuleUpdate) Where(ps ...predicate.Module) *ModuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *ModuleUpdate) SetName(v string) *ModuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModuleUpdate) SetNillableName(v *string) *ModuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *ModuleUpdate) SetActive(v bool) *ModuleUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *ModuleUpdate) SetNillableActive(v *bool) *ModuleUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddAccountPlanIDs adds the "account_plans" edge to the AccountPlan entity by IDs.
func (_u *ModuleUpdate) AddAccountPlanIDs(ids ...uuid.UUID) *ModuleUpdate {
	_u.mutation.AddAccountPlanIDs(ids...)
	return _u
}

// AddAccountPlans adds the "account_plans" edges to the AccountPlan entity.
func (_u *ModuleUpdate) AddAccountPlans(v ...*AccountPlan) *ModuleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountPlanIDs(ids...)
}

// Mutation returns the ModuleMutation object of the builder.
func (_u *ModuleUpdate) Mutation() *ModuleMutation {
	return _u.mutation
}

// ClearAccountPlans clears all "account_plans" edges to the AccountPlan entity.
func (_u *ModuleUpdate) ClearAccountPlans() *ModuleUpdate {
	_u.mutation.ClearAccountPlans()
	return _u
}

// RemoveAccountPlanIDs removes the "account_plans" edge to AccountPlan entities by IDs.
func (_u *ModuleUpdate) RemoveAccountPlanIDs(ids ...uuid.UUID) *ModuleUpdate {
	_u.mutation.RemoveAccountPlanIDs(ids...)
	return _u
}

// RemoveAccountPlans removes "account_plans" edges to AccountPlan entities.
func (_u *ModuleUpdate) RemoveAccountPlans(v ...*AccountPlan) *ModuleUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountPlanIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModuleUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := module.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Module.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ModuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(module.Table, module.Columns, sqlgraph.NewFieldSpec(module.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(module.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(module.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.AccountPlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   module.AccountPlansTable,
			Columns: module.AccountPlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountPlansIDs(); len(nodes) > 0 && !_u.mutation.AccountPlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   module.AccountPlansTable,
			Columns: module.AccountPlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountPlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   module.AccountPlansTable,
			Columns: module.AccountPlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{module.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModuleUpdateOne is the builder for updating a single Module entity.
type ModuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModuleMutation
}

// SetName sets the "name" field.
func (_u *ModuleUpdateOne) SetName(v string) *ModuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ModuleUpdateOne) SetNillableName(v *string) *ModuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetActive sets the "active" field.
func (_u *ModuleUpdateOne) SetActive(v bool) *ModuleUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *ModuleUpdateOne) SetNillableActive(v *bool) *ModuleUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// AddAccountPlanIDs adds the "account_plans" edge to the AccountPlan entity by IDs.
func (_u *ModuleUpdateOne) AddAccountPlanIDs(ids ...uuid.UUID) *ModuleUpdateOne {
	_u.mutation.AddAccountPlanIDs(ids...)
	return _u
}

// AddAccountPlans adds the "account_plans" edges to the AccountPlan entity.
func (_u *ModuleUpdateOne) AddAccountPlans(v ...*AccountPlan) *ModuleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountPlanIDs(ids...)
}

// Mutation returns the ModuleMutation object of the builder.
func (_u *ModuleUpdateOne) Mutation() *ModuleMutation {
	return _u.mutation
}

// ClearAccountPlans clears all "account_plans" edges to the AccountPlan entity.
func (_u *ModuleUpdateOne) ClearAccountPlans() *ModuleUpdateOne {
	_u.mutation.ClearAccountPlans()
	return _u
}

// RemoveAccountPlanIDs removes the "account_plans" edge to AccountPlan entities by IDs.
func (_u *ModuleUpdateOne) RemoveAccountPlanIDs(ids ...uuid.UUID) *ModuleUpdateOne {
	_u.mutation.RemoveAccountPlanIDs(ids...)
	return _u
}

// RemoveAccountPlans removes "account_plans" edges to AccountPlan entities.
func (_u *ModuleUpdateOne) RemoveAccountPlans(v ...*AccountPlan) *ModuleUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountPlanIDs(ids...)
}

// Where appends a list predicates to the ModuleUpdate builder.
func (_u *ModuleUpdateOne) Where(ps ...predicate.Module) *ModuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModuleUpdateOne) Select(field string, fields ...string) *ModuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Module entity.
func (_u *ModuleUpdateOne) Save(ctx context.Context) (*Module, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModuleUpdateOne) SaveX(ctx context.Context) *Module {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ModuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := module.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Module.name": %w`, err)}
		}
	}
	return nil
}

func (_u *ModuleUpdateOne) sqlSave(ctx context.Context) (_node *Module, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(module.Table, module.Columns, sqlgraph.NewFieldSpec(module.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Module.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, module.FieldID)
		for _, f := range fields {
			if !module.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != module.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(module.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(module.FieldActive, field.TypeBool, value)
	}
	if _u.mutation.AccountPlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   module.AccountPlansTable,
			Columns: module.AccountPlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountPlansIDs(); len(nodes) > 0 && !_u.mutation.AccountPlansCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   module.AccountPlansTable,
			Columns: module.AccountPlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountPlansIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   module.AccountPlansTable,
			Columns: module.AccountPlansPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(accountplan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Module{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{module.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
