// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/plan"
	"github.com/joaofilippe/subclub/ent/predicate"
	"github.com/joaofilippe/subclub/ent/subscription"
)

// PlanUpdate is the builder for updating Plan entities.
type PlanUpdate struct {
	config
	hooks    []Hook
	mutation *PlanMutation
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdate) Where(ps ...predicate.Plan) *PlanUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCode sets the "code" field.
func (_u *PlanUpdate) SetCode(v string) *PlanUpdate {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableCode(v *string) *PlanUpdate {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PlanUpdate) SetName(v string) *PlanUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableName(v *string) *PlanUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlanUpdate) SetDescription(v string) *PlanUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableDescription(v *string) *PlanUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlanUpdate) ClearDescription() *PlanUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetProductValue sets the "product_value" field.
func (_u *PlanUpdate) SetProductValue(v float64) *PlanUpdate {
	_u.mutation.ResetProductValue()
	_u.mutation.SetProductValue(v)
	return _u
}

// SetNillableProductValue sets the "product_value" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableProductValue(v *float64) *PlanUpdate {
	if v != nil {
		_u.SetProductValue(*v)
	}
	return _u
}

// AddProductValue adds value to the "product_value" field.
func (_u *PlanUpdate) AddProductValue(v float64) *PlanUpdate {
	_u.mutation.AddProductValue(v)
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *PlanUpdate) SetDiscountValue(v float64) *PlanUpdate {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableDiscountValue(v *float64) *PlanUpdate {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *PlanUpdate) AddDiscountValue(v float64) *PlanUpdate {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PlanUpdate) SetPrice(v float64) *PlanUpdate {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PlanUpdate) SetNillablePrice(v *float64) *PlanUpdate {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PlanUpdate) AddPrice(v float64) *PlanUpdate {
	_u.mutation.AddPrice(v)
	return _u
}

// SetIntervalDays sets the "interval_days" field.
func (_u *PlanUpdate) SetIntervalDays(v int) *PlanUpdate {
	_u.mutation.ResetIntervalDays()
	_u.mutation.SetIntervalDays(v)
	return _u
}

// SetNillableIntervalDays sets the "interval_days" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableIntervalDays(v *int) *PlanUpdate {
	if v != nil {
		_u.SetIntervalDays(*v)
	}
	return _u
}

// AddIntervalDays adds value to the "interval_days" field.
func (_u *PlanUpdate) AddIntervalDays(v int) *PlanUpdate {
	_u.mutation.AddIntervalDays(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *PlanUpdate) SetActive(v bool) *PlanUpdate {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableActive(v *bool) *PlanUpdate {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *PlanUpdate) SetImageURL(v string) *PlanUpdate {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *PlanUpdate) SetNillableImageURL(v *string) *PlanUpdate {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *PlanUpdate) ClearImageURL() *PlanUpdate {
	_u.mutation.ClearImageURL()
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *PlanUpdate) AddSubscriptionIDs(ids ...uuid.UUID) *PlanUpdate {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdate) AddSubscriptions(v ...*Subscription) *PlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdate) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdate) ClearSubscriptions() *PlanUpdate {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *PlanUpdate) RemoveSubscriptionIDs(ids ...uuid.UUID) *PlanUpdate {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *PlanUpdate) RemoveSubscriptions(v ...*Subscription) *PlanUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PlanUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PlanUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdate) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := plan.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Plan.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(plan.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(plan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ProductValue(); ok {
		_spec.SetField(plan.FieldProductValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProductValue(); ok {
		_spec.AddField(plan.FieldProductValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(plan.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(plan.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IntervalDays(); ok {
		_spec.SetField(plan.FieldIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalDays(); ok {
		_spec.AddField(plan.FieldIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(plan.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(plan.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(plan.FieldImageURL, field.TypeString)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PlanUpdateOne is the builder for updating a single Plan entity.
type PlanUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PlanMutation
}

// SetCode sets the "code" field.
func (_u *PlanUpdateOne) SetCode(v string) *PlanUpdateOne {
	_u.mutation.SetCode(v)
	return _u
}

// SetNillableCode sets the "code" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableCode(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetCode(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *PlanUpdateOne) SetName(v string) *PlanUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableName(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *PlanUpdateOne) SetDescription(v string) *PlanUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableDescription(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PlanUpdateOne) ClearDescription() *PlanUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetProductValue sets the "product_value" field.
func (_u *PlanUpdateOne) SetProductValue(v float64) *PlanUpdateOne {
	_u.mutation.ResetProductValue()
	_u.mutation.SetProductValue(v)
	return _u
}

// SetNillableProductValue sets the "product_value" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableProductValue(v *float64) *PlanUpdateOne {
	if v != nil {
		_u.SetProductValue(*v)
	}
	return _u
}

// AddProductValue adds value to the "product_value" field.
func (_u *PlanUpdateOne) AddProductValue(v float64) *PlanUpdateOne {
	_u.mutation.AddProductValue(v)
	return _u
}

// SetDiscountValue sets the "discount_value" field.
func (_u *PlanUpdateOne) SetDiscountValue(v float64) *PlanUpdateOne {
	_u.mutation.ResetDiscountValue()
	_u.mutation.SetDiscountValue(v)
	return _u
}

// SetNillableDiscountValue sets the "discount_value" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableDiscountValue(v *float64) *PlanUpdateOne {
	if v != nil {
		_u.SetDiscountValue(*v)
	}
	return _u
}

// AddDiscountValue adds value to the "discount_value" field.
func (_u *PlanUpdateOne) AddDiscountValue(v float64) *PlanUpdateOne {
	_u.mutation.AddDiscountValue(v)
	return _u
}

// SetPrice sets the "price" field.
func (_u *PlanUpdateOne) SetPrice(v float64) *PlanUpdateOne {
	_u.mutation.ResetPrice()
	_u.mutation.SetPrice(v)
	return _u
}

// SetNillablePrice sets the "price" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillablePrice(v *float64) *PlanUpdateOne {
	if v != nil {
		_u.SetPrice(*v)
	}
	return _u
}

// AddPrice adds value to the "price" field.
func (_u *PlanUpdateOne) AddPrice(v float64) *PlanUpdateOne {
	_u.mutation.AddPrice(v)
	return _u
}

// SetIntervalDays sets the "interval_days" field.
func (_u *PlanUpdateOne) SetIntervalDays(v int) *PlanUpdateOne {
	_u.mutation.ResetIntervalDays()
	_u.mutation.SetIntervalDays(v)
	return _u
}

// SetNillableIntervalDays sets the "interval_days" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableIntervalDays(v *int) *PlanUpdateOne {
	if v != nil {
		_u.SetIntervalDays(*v)
	}
	return _u
}

// AddIntervalDays adds value to the "interval_days" field.
func (_u *PlanUpdateOne) AddIntervalDays(v int) *PlanUpdateOne {
	_u.mutation.AddIntervalDays(v)
	return _u
}

// SetActive sets the "active" field.
func (_u *PlanUpdateOne) SetActive(v bool) *PlanUpdateOne {
	_u.mutation.SetActive(v)
	return _u
}

// SetNillableActive sets the "active" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableActive(v *bool) *PlanUpdateOne {
	if v != nil {
		_u.SetActive(*v)
	}
	return _u
}

// SetImageURL sets the "image_url" field.
func (_u *PlanUpdateOne) SetImageURL(v string) *PlanUpdateOne {
	_u.mutation.SetImageURL(v)
	return _u
}

// SetNillableImageURL sets the "image_url" field if the given value is not nil.
func (_u *PlanUpdateOne) SetNillableImageURL(v *string) *PlanUpdateOne {
	if v != nil {
		_u.SetImageURL(*v)
	}
	return _u
}

// ClearImageURL clears the value of the "image_url" field.
func (_u *PlanUpdateOne) ClearImageURL() *PlanUpdateOne {
	_u.mutation.ClearImageURL()
	return _u
}

// AddSubscriptionIDs adds the "subscriptions" edge to the Subscription entity by IDs.
func (_u *PlanUpdateOne) AddSubscriptionIDs(ids ...uuid.UUID) *PlanUpdateOne {
	_u.mutation.AddSubscriptionIDs(ids...)
	return _u
}

// AddSubscriptions adds the "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdateOne) AddSubscriptions(v ...*Subscription) *PlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSubscriptionIDs(ids...)
}

// Mutation returns the PlanMutation object of the builder.
func (_u *PlanUpdateOne) Mutation() *PlanMutation {
	return _u.mutation
}

// ClearSubscriptions clears all "subscriptions" edges to the Subscription entity.
func (_u *PlanUpdateOne) ClearSubscriptions() *PlanUpdateOne {
	_u.mutation.ClearSubscriptions()
	return _u
}

// RemoveSubscriptionIDs removes the "subscriptions" edge to Subscription entities by IDs.
func (_u *PlanUpdateOne) RemoveSubscriptionIDs(ids ...uuid.UUID) *PlanUpdateOne {
	_u.mutation.RemoveSubscriptionIDs(ids...)
	return _u
}

// RemoveSubscriptions removes "subscriptions" edges to Subscription entities.
func (_u *PlanUpdateOne) RemoveSubscriptions(v ...*Subscription) *PlanUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSubscriptionIDs(ids...)
}

// Where appends a list predicates to the PlanUpdate builder.
func (_u *PlanUpdateOne) Where(ps ...predicate.Plan) *PlanUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PlanUpdateOne) Select(field string, fields ...string) *PlanUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Plan entity.
func (_u *PlanUpdateOne) Save(ctx context.Context) (*Plan, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PlanUpdateOne) SaveX(ctx context.Context) *Plan {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PlanUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PlanUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PlanUpdateOne) check() error {
	if v, ok := _u.mutation.Code(); ok {
		if err := plan.CodeValidator(v); err != nil {
			return &ValidationError{Name: "code", err: fmt.Errorf(`ent: validator failed for field "Plan.code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := plan.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Plan.name": %w`, err)}
		}
	}
	return nil
}

func (_u *PlanUpdateOne) sqlSave(ctx context.Context) (_node *Plan, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(plan.Table, plan.Columns, sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Plan.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plan.FieldID)
		for _, f := range fields {
			if !plan.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != plan.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Code(); ok {
		_spec.SetField(plan.FieldCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(plan.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(plan.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(plan.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ProductValue(); ok {
		_spec.SetField(plan.FieldProductValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedProductValue(); ok {
		_spec.AddField(plan.FieldProductValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.DiscountValue(); ok {
		_spec.SetField(plan.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedDiscountValue(); ok {
		_spec.AddField(plan.FieldDiscountValue, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Price(); ok {
		_spec.SetField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedPrice(); ok {
		_spec.AddField(plan.FieldPrice, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.IntervalDays(); ok {
		_spec.SetField(plan.FieldIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalDays(); ok {
		_spec.AddField(plan.FieldIntervalDays, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Active(); ok {
		_spec.SetField(plan.FieldActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ImageURL(); ok {
		_spec.SetField(plan.FieldImageURL, field.TypeString, value)
	}
	if _u.mutation.ImageURLCleared() {
		_spec.ClearField(plan.FieldImageURL, field.TypeString)
	}
	if _u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSubscriptionsIDs(); len(nodes) > 0 && !_u.mutation.SubscriptionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SubscriptionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   plan.SubscriptionsTable,
			Columns: []string{plan.SubscriptionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Plan{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{plan.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
