// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/joaofilippe/subclub/ent/customer"
	"github.com/joaofilippe/subclub/ent/plan"
	"github.com/joaofilippe/subclub/ent/predicate"
	"github.com/joaofilippe/subclub/ent/subscription"
)

// SubscriptionUpdate is the builder for updating Subscription entities.
type SubscriptionUpdate struct {
	config
	hooks    []Hook
	mutation *SubscriptionMutation
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdate) Where(ps ...predicate.Subscription) *SubscriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *SubscriptionUpdate) SetClientID(v uuid.UUID) *SubscriptionUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableClientID(v *uuid.UUID) *SubscriptionUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *SubscriptionUpdate) ClearClientID() *SubscriptionUpdate {
	_u.mutation.ClearClientID()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *SubscriptionUpdate) SetPlanID(v uuid.UUID) *SubscriptionUpdate {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillablePlanID(v *uuid.UUID) *SubscriptionUpdate {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *SubscriptionUpdate) ClearPlanID() *SubscriptionUpdate {
	_u.mutation.ClearPlanID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdate) SetStatus(v string) *SubscriptionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStatus(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetShipmentStatus sets the "shipment_status" field.
func (_u *SubscriptionUpdate) SetShipmentStatus(v string) *SubscriptionUpdate {
	_u.mutation.SetShipmentStatus(v)
	return _u
}

// SetNillableShipmentStatus sets the "shipment_status" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableShipmentStatus(v *string) *SubscriptionUpdate {
	if v != nil {
		_u.SetShipmentStatus(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *SubscriptionUpdate) SetStartDate(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableStartDate(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetNextBillingDate sets the "next_billing_date" field.
func (_u *SubscriptionUpdate) SetNextBillingDate(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetNextBillingDate(v)
	return _u
}

// SetNillableNextBillingDate sets the "next_billing_date" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableNextBillingDate(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetNextBillingDate(*v)
	}
	return _u
}

// ClearNextBillingDate clears the value of the "next_billing_date" field.
func (_u *SubscriptionUpdate) ClearNextBillingDate() *SubscriptionUpdate {
	_u.mutation.ClearNextBillingDate()
	return _u
}

// SetNextShipmentDate sets the "next_shipment_date" field.
func (_u *SubscriptionUpdate) SetNextShipmentDate(v time.Time) *SubscriptionUpdate {
	_u.mutation.SetNextShipmentDate(v)
	return _u
}

// SetNillableNextShipmentDate sets the "next_shipment_date" field if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableNextShipmentDate(v *time.Time) *SubscriptionUpdate {
	if v != nil {
		_u.SetNextShipmentDate(*v)
	}
	return _u
}

// ClearNextShipmentDate clears the value of the "next_shipment_date" field.
func (_u *SubscriptionUpdate) ClearNextShipmentDate() *SubscriptionUpdate {
	_u.mutation.ClearNextShipmentDate()
	return _u
}

// SetCustomerID sets the "customer" edge to the Customer entity by ID.
func (_u *SubscriptionUpdate) SetCustomerID(id uuid.UUID) *SubscriptionUpdate {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetNillableCustomerID sets the "customer" edge to the Customer entity by ID if the given value is not nil.
func (_u *SubscriptionUpdate) SetNillableCustomerID(id *uuid.UUID) *SubscriptionUpdate {
	if id != nil {
		_u = _u.SetCustomerID(*id)
	}
	return _u
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *SubscriptionUpdate) SetCustomer(v *Customer) *SubscriptionUpdate {
	return _u.SetCustomerID(v.ID)
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdate) SetPlan(v *Plan) *SubscriptionUpdate {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdate) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *SubscriptionUpdate) ClearCustomer() *SubscriptionUpdate {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdate) ClearPlan() *SubscriptionUpdate {
	_u.mutation.ClearPlan()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SubscriptionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SubscriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SubscriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShipmentStatus(); ok {
		_spec.SetField(subscription.FieldShipmentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(subscription.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextBillingDate(); ok {
		_spec.SetField(subscription.FieldNextBillingDate, field.TypeTime, value)
	}
	if _u.mutation.NextBillingDateCleared() {
		_spec.ClearField(subscription.FieldNextBillingDate, field.TypeTime)
	}
	if value, ok := _u.mutation.NextShipmentDate(); ok {
		_spec.SetField(subscription.FieldNextShipmentDate, field.TypeTime, value)
	}
	if _u.mutation.NextShipmentDateCleared() {
		_spec.ClearField(subscription.FieldNextShipmentDate, field.TypeTime)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SubscriptionUpdateOne is the builder for updating a single Subscription entity.
type SubscriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SubscriptionMutation
}

// SetClientID sets the "client_id" field.
func (_u *SubscriptionUpdateOne) SetClientID(v uuid.UUID) *SubscriptionUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableClientID(v *uuid.UUID) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// ClearClientID clears the value of the "client_id" field.
func (_u *SubscriptionUpdateOne) ClearClientID() *SubscriptionUpdateOne {
	_u.mutation.ClearClientID()
	return _u
}

// SetPlanID sets the "plan_id" field.
func (_u *SubscriptionUpdateOne) SetPlanID(v uuid.UUID) *SubscriptionUpdateOne {
	_u.mutation.SetPlanID(v)
	return _u
}

// SetNillablePlanID sets the "plan_id" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillablePlanID(v *uuid.UUID) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetPlanID(*v)
	}
	return _u
}

// ClearPlanID clears the value of the "plan_id" field.
func (_u *SubscriptionUpdateOne) ClearPlanID() *SubscriptionUpdateOne {
	_u.mutation.ClearPlanID()
	return _u
}

// SetStatus sets the "status" field.
func (_u *SubscriptionUpdateOne) SetStatus(v string) *SubscriptionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStatus(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetShipmentStatus sets the "shipment_status" field.
func (_u *SubscriptionUpdateOne) SetShipmentStatus(v string) *SubscriptionUpdateOne {
	_u.mutation.SetShipmentStatus(v)
	return _u
}

// SetNillableShipmentStatus sets the "shipment_status" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableShipmentStatus(v *string) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetShipmentStatus(*v)
	}
	return _u
}

// SetStartDate sets the "start_date" field.
func (_u *SubscriptionUpdateOne) SetStartDate(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetStartDate(v)
	return _u
}

// SetNillableStartDate sets the "start_date" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableStartDate(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetStartDate(*v)
	}
	return _u
}

// SetNextBillingDate sets the "next_billing_date" field.
func (_u *SubscriptionUpdateOne) SetNextBillingDate(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetNextBillingDate(v)
	return _u
}

// SetNillableNextBillingDate sets the "next_billing_date" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableNextBillingDate(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetNextBillingDate(*v)
	}
	return _u
}

// ClearNextBillingDate clears the value of the "next_billing_date" field.
func (_u *SubscriptionUpdateOne) ClearNextBillingDate() *SubscriptionUpdateOne {
	_u.mutation.ClearNextBillingDate()
	return _u
}

// SetNextShipmentDate sets the "next_shipment_date" field.
func (_u *SubscriptionUpdateOne) SetNextShipmentDate(v time.Time) *SubscriptionUpdateOne {
	_u.mutation.SetNextShipmentDate(v)
	return _u
}

// SetNillableNextShipmentDate sets the "next_shipment_date" field if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableNextShipmentDate(v *time.Time) *SubscriptionUpdateOne {
	if v != nil {
		_u.SetNextShipmentDate(*v)
	}
	return _u
}

// ClearNextShipmentDate clears the value of the "next_shipment_date" field.
func (_u *SubscriptionUpdateOne) ClearNextShipmentDate() *SubscriptionUpdateOne {
	_u.mutation.ClearNextShipmentDate()
	return _u
}

// SetCustomerID sets the "customer" edge to the Customer entity by ID.
func (_u *SubscriptionUpdateOne) SetCustomerID(id uuid.UUID) *SubscriptionUpdateOne {
	_u.mutation.SetCustomerID(id)
	return _u
}

// SetNillableCustomerID sets the "customer" edge to the Customer entity by ID if the given value is not nil.
func (_u *SubscriptionUpdateOne) SetNillableCustomerID(id *uuid.UUID) *SubscriptionUpdateOne {
	if id != nil {
		_u = _u.SetCustomerID(*id)
	}
	return _u
}

// SetCustomer sets the "customer" edge to the Customer entity.
func (_u *SubscriptionUpdateOne) SetCustomer(v *Customer) *SubscriptionUpdateOne {
	return _u.SetCustomerID(v.ID)
}

// SetPlan sets the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdateOne) SetPlan(v *Plan) *SubscriptionUpdateOne {
	return _u.SetPlanID(v.ID)
}

// Mutation returns the SubscriptionMutation object of the builder.
func (_u *SubscriptionUpdateOne) Mutation() *SubscriptionMutation {
	return _u.mutation
}

// ClearCustomer clears the "customer" edge to the Customer entity.
func (_u *SubscriptionUpdateOne) ClearCustomer() *SubscriptionUpdateOne {
	_u.mutation.ClearCustomer()
	return _u
}

// ClearPlan clears the "plan" edge to the Plan entity.
func (_u *SubscriptionUpdateOne) ClearPlan() *SubscriptionUpdateOne {
	_u.mutation.ClearPlan()
	return _u
}

// Where appends a list predicates to the SubscriptionUpdate builder.
func (_u *SubscriptionUpdateOne) Where(ps ...predicate.Subscription) *SubscriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SubscriptionUpdateOne) Select(field string, fields ...string) *SubscriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Subscription entity.
func (_u *SubscriptionUpdateOne) Save(ctx context.Context) (*Subscription, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) SaveX(ctx context.Context) *Subscription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SubscriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SubscriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SubscriptionUpdateOne) sqlSave(ctx context.Context) (_node *Subscription, err error) {
	_spec := sqlgraph.NewUpdateSpec(subscription.Table, subscription.Columns, sqlgraph.NewFieldSpec(subscription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Subscription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, subscription.FieldID)
		for _, f := range fields {
			if !subscription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != subscription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(subscription.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.ShipmentStatus(); ok {
		_spec.SetField(subscription.FieldShipmentStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.StartDate(); ok {
		_spec.SetField(subscription.FieldStartDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.NextBillingDate(); ok {
		_spec.SetField(subscription.FieldNextBillingDate, field.TypeTime, value)
	}
	if _u.mutation.NextBillingDateCleared() {
		_spec.ClearField(subscription.FieldNextBillingDate, field.TypeTime)
	}
	if value, ok := _u.mutation.NextShipmentDate(); ok {
		_spec.SetField(subscription.FieldNextShipmentDate, field.TypeTime, value)
	}
	if _u.mutation.NextShipmentDateCleared() {
		_spec.ClearField(subscription.FieldNextShipmentDate, field.TypeTime)
	}
	if _u.mutation.CustomerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.CustomerTable,
			Columns: []string{subscription.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customer.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PlanCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PlanIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   subscription.PlanTable,
			Columns: []string{subscription.PlanColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plan.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Subscription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{subscription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
