// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/joaofilippe/subclub/ent/predicate"
	"github.com/joaofilippe/subclub/ent/systemuser"
)

// SystemUserUpdate is the builder for updating SystemUser entities.
type SystemUserUpdate struct {
	config
	hooks    []Hook
	mutation *SystemUserMutation
}

// Where appends a list predicates to the SystemUserUpdate builder.
func (_u *SystemUserUpdate) Where(ps ...predicate.SystemUser) *SystemUserUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *SystemUserUpdate) SetName(v string) *SystemUserUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SystemUserUpdate) SetNillableName(v *string) *SystemUserUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *SystemUserUpdate) SetEmail(v string) *SystemUserUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SystemUserUpdate) SetNillableEmail(v *string) *SystemUserUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *SystemUserUpdate) SetPassword(v string) *SystemUserUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *SystemUserUpdate) SetNillablePassword(v *string) *SystemUserUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SystemUserUpdate) SetType(v systemuser.Type) *SystemUserUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SystemUserUpdate) SetNillableType(v *systemuser.Type) *SystemUserUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *SystemUserUpdate) SetRole(v systemuser.Role) *SystemUserUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SystemUserUpdate) SetNillableRole(v *systemuser.Role) *SystemUserUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemUserUpdate) SetUpdatedAt(v time.Time) *SystemUserUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SystemUserUpdate) SetDeletedAt(v time.Time) *SystemUserUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SystemUserUpdate) SetNillableDeletedAt(v *time.Time) *SystemUserUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SystemUserUpdate) ClearDeletedAt() *SystemUserUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the SystemUserMutation object of the builder.
func (_u *SystemUserUpdate) Mutation() *SystemUserMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SystemUserUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemUserUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SystemUserUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemUserUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemUserUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemUserUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := systemuser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SystemUser.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := systemuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SystemUser.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := systemuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "SystemUser.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := systemuser.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SystemUser.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := systemuser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SystemUser.role": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemUserUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemuser.Table, systemuser.Columns, sqlgraph.NewFieldSpec(systemuser.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(systemuser.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(systemuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(systemuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(systemuser.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(systemuser.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(systemuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(systemuser.FieldDeletedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SystemUserUpdateOne is the builder for updating a single SystemUser entity.
type SystemUserUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SystemUserMutation
}

// SetName sets the "name" field.
func (_u *SystemUserUpdateOne) SetName(v string) *SystemUserUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *SystemUserUpdateOne) SetNillableName(v *string) *SystemUserUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *SystemUserUpdateOne) SetEmail(v string) *SystemUserUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *SystemUserUpdateOne) SetNillableEmail(v *string) *SystemUserUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetPassword sets the "password" field.
func (_u *SystemUserUpdateOne) SetPassword(v string) *SystemUserUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *SystemUserUpdateOne) SetNillablePassword(v *string) *SystemUserUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *SystemUserUpdateOne) SetType(v systemuser.Type) *SystemUserUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *SystemUserUpdateOne) SetNillableType(v *systemuser.Type) *SystemUserUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *SystemUserUpdateOne) SetRole(v systemuser.Role) *SystemUserUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *SystemUserUpdateOne) SetNillableRole(v *systemuser.Role) *SystemUserUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SystemUserUpdateOne) SetUpdatedAt(v time.Time) *SystemUserUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *SystemUserUpdateOne) SetDeletedAt(v time.Time) *SystemUserUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *SystemUserUpdateOne) SetNillableDeletedAt(v *time.Time) *SystemUserUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *SystemUserUpdateOne) ClearDeletedAt() *SystemUserUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// Mutation returns the SystemUserMutation object of the builder.
func (_u *SystemUserUpdateOne) Mutation() *SystemUserMutation {
	return _u.mutation
}

// Where appends a list predicates to the SystemUserUpdate builder.
func (_u *SystemUserUpdateOne) Where(ps ...predicate.SystemUser) *SystemUserUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SystemUserUpdateOne) Select(field string, fields ...string) *SystemUserUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SystemUser entity.
func (_u *SystemUserUpdateOne) Save(ctx context.Context) (*SystemUser, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SystemUserUpdateOne) SaveX(ctx context.Context) *SystemUser {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SystemUserUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SystemUserUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SystemUserUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := systemuser.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SystemUserUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := systemuser.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "SystemUser.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Email(); ok {
		if err := systemuser.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "SystemUser.email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := systemuser.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "SystemUser.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GetType(); ok {
		if err := systemuser.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "SystemUser.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Role(); ok {
		if err := systemuser.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "SystemUser.role": %w`, err)}
		}
	}
	return nil
}

func (_u *SystemUserUpdateOne) sqlSave(ctx context.Context) (_node *SystemUser, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(systemuser.Table, systemuser.Columns, sqlgraph.NewFieldSpec(systemuser.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SystemUser.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, systemuser.FieldID)
		for _, f := range fields {
			if !systemuser.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != systemuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(systemuser.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(systemuser.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(systemuser.FieldPassword, field.TypeString, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(systemuser.FieldType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(systemuser.FieldRole, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(systemuser.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(systemuser.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(systemuser.FieldDeletedAt, field.TypeTime)
	}
	_node = &SystemUser{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{systemuser.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
