// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Account is the predicate function for account builders.
type Account func(*sql.Selector)

// AccountPlan is the predicate function for accountplan builders.
type AccountPlan func(*sql.Selector)

// Customer is the predicate function for customer builders.
type Customer func(*sql.Selector)

// Module is the predicate function for module builders.
type Module func(*sql.Selector)

// Plan is the predicate function for plan builders.
type Plan func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Subscription is the predicate function for subscription builders.
type Subscription func(*sql.Selector)

// SystemUser is the predicate function for systemuser builders.
type SystemUser func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
